"""Build the constructed deliverable templates in registry/templates/ (ADR-0001 §Q11).

    python ops/templates/make_templates.py            # writes only the templates that are missing
    python ops/templates/make_templates.py --force    # rewrites every template

"Fix the template first, by hand, as an artefact nobody may simplify; then make the
generator match it." These files ARE that fixed artefact: letterhead, classification
markings in header and footer, a document-control table, the declared sections, a
sources table, an approval block with signature lines, and a revision-history table.
They are committed; the generator (citadel_deliverables) only ever fills placeholders
in them and never builds layout of its own, so a real organisational template with the
same placeholders replaces one of these with no code change.

Placeholder convention: `{{key}}` alone in a paragraph is a block placeholder (a
section's content goes there); `{{key}}` inside other text is an inline field; a table
row containing `{{key}}` is a row template the generator repeats.
"""

from __future__ import annotations

from pathlib import Path

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Mm, Pt, RGBColor
from docx.table import Table
from docx.text.paragraph import Paragraph
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

OUT = Path(__file__).resolve().parents[2] / "registry" / "templates"
NAVY = RGBColor(0x1D, 0x2B, 0x3A)
RED = RGBColor(0xB0, 0x1C, 0x24)


def _field(paragraph: Paragraph, instruction: str) -> None:
    """A Word field (PAGE / NUMPAGES) -- python-docx has no API for these."""
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    text = OxmlElement("w:instrText")
    text.set(qn("xml:space"), "preserve")
    text.text = instruction
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.append(begin)
    run._r.append(text)
    run._r.append(end)


def _shade(cell_paragraph_parent: object, fill: str) -> None:
    tc_pr = cell_paragraph_parent._tc.get_or_add_tcPr()  # type: ignore[attr-defined]
    shading = OxmlElement("w:shd")
    shading.set(qn("w:val"), "clear")
    shading.set(qn("w:color"), "auto")
    shading.set(qn("w:fill"), fill)
    tc_pr.append(shading)


def _run(paragraph: Paragraph, text: str, *, bold: bool = False, size: float = 10.5, color: RGBColor | None = None) -> None:
    run = paragraph.add_run(text)
    run.bold = bold
    run.font.size = Pt(size)
    if color is not None:
        run.font.color.rgb = color


def _header_footer(document: Document, title: str) -> None:
    section = document.sections[0]
    section.page_height, section.page_width = Mm(297), Mm(210)
    section.left_margin = section.right_margin = Mm(20)
    section.top_margin, section.bottom_margin = Mm(24), Mm(20)

    header = section.header.paragraphs[0]
    header.text = ""
    _run(header, "{{org_name}}", bold=True, size=9, color=NAVY)
    _run(header, "\t\t", size=9)
    _run(header, "{{classification}}", bold=True, size=10, color=RED)
    footer = section.footer.paragraphs[0]
    footer.text = ""
    _run(footer, "{{classification}}", bold=True, size=8, color=RED)
    _run(footer, f"  |  {title} {{{{doc_number}}}} rev {{{{revision}}}}  |  generated by Citadel, task {{{{task_ref}}}}  |  page ", size=8)
    _field(footer, "PAGE")
    _run(footer, " of ", size=8)
    _field(footer, "NUMPAGES")


def _banner(document: Document, title: str) -> None:
    marking = document.add_paragraph()
    marking.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    _run(marking, "{{classification}}", bold=True, size=11, color=RED)
    heading = document.add_paragraph()
    _run(heading, title, bold=True, size=18, color=NAVY)
    sub = document.add_paragraph()
    _run(sub, "{{subject_line}}", size=11)


def _control_table(document: Document, extra: list[tuple[str, str]]) -> None:
    rows = [("Document No.", "{{doc_number}}"), ("Revision", "{{revision}}"), ("Date", "{{date}}"),
            ("Prepared by", "{{prepared_by}}"), ("Citadel task", "{{task_ref}}"), *extra]
    table = document.add_table(rows=len(rows), cols=2)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    for i, (label, value) in enumerate(rows):
        label_cell, value_cell = table.rows[i].cells
        label_cell.width, value_cell.width = Mm(45), Mm(125)
        label_cell.paragraphs[0].text = ""
        _run(label_cell.paragraphs[0], label, bold=True, size=9.5)
        _shade(label_cell, "E8EDF3")
        value_cell.paragraphs[0].text = ""
        _run(value_cell.paragraphs[0], value, size=9.5)
    document.add_paragraph()


def _section(document: Document, number: int, title: str, key: str) -> None:
    heading = document.add_paragraph()
    heading.paragraph_format.space_before = Pt(10)
    _run(heading, f"{number}. {title}", bold=True, size=12, color=NAVY)
    body = document.add_paragraph()
    _run(body, "{{" + key + "}}")


def _row_table(document: Document, headers: list[str], placeholder: str, widths_mm: list[int]) -> Table:
    table = document.add_table(rows=2, cols=len(headers))
    table.style = "Table Grid"
    for i, text in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.width = Mm(widths_mm[i])
        cell.paragraphs[0].text = ""
        _run(cell.paragraphs[0], text, bold=True, size=9)
        _shade(cell, "D9E2EC")
    for i in range(len(headers)):
        cell = table.rows[1].cells[i]
        cell.width = Mm(widths_mm[i])
        cell.paragraphs[0].text = ""
        _run(cell.paragraphs[0], "{{" + placeholder + "." + str(i) + "}}", size=9)
    return table


def _sources(document: Document, number: int | None) -> None:
    heading = document.add_paragraph()
    heading.paragraph_format.space_before = Pt(10)
    _run(heading, f"{number}. Sources" if number else "Sources", bold=True, size=12, color=NAVY)
    note = document.add_paragraph()
    _run(note, "Each bracketed reference in this document resolves to the source below: the exact "
               "document version, page and region the statement was drawn from.", size=8.5)
    _row_table(document, ["Ref", "Source document", "Version", "Page", "Region (x0, y0, x1, y1)"], "sources", [14, 86, 18, 14, 38])


def _approval_block(document: Document) -> None:
    heading = document.add_paragraph()
    heading.paragraph_format.space_before = Pt(12)
    _run(heading, "Approval", bold=True, size=12, color=NAVY)
    table = document.add_table(rows=4, cols=4)
    table.style = "Table Grid"
    for i, text in enumerate(["Role", "Name", "Signature", "Date"]):
        cell = table.rows[0].cells[i]
        cell.paragraphs[0].text = ""
        _run(cell.paragraphs[0], text, bold=True, size=9)
        _shade(cell, "D9E2EC")
    rows = [("Prepared by", "{{prepared_by}}", "{{prepared_signature}}", "{{date}}"),
            ("Reviewed by", "{{reviewed_by}}", "{{reviewed_signature}}", "{{reviewed_on}}"),
            ("Approved by", "{{approved_by}}", "{{approved_signature}}", "{{approved_on}}")]
    for r, values in enumerate(rows, start=1):
        for c, value in enumerate(values):
            cell = table.rows[r].cells[c]
            cell.paragraphs[0].text = ""
            _run(cell.paragraphs[0], value, bold=(c == 0), size=9)
    # An approval block split across a page break invites a signature under the wrong
    # text: keep the heading and every row but the last with the next.
    heading.paragraph_format.keep_with_next = True
    for row in table.rows[:-1]:
        for cell in row.cells:
            cell.paragraphs[0].paragraph_format.keep_with_next = True
    for row in table.rows:
        tr_pr = row._tr.get_or_add_trPr()
        cant_split = OxmlElement("w:cantSplit")
        tr_pr.append(cant_split)


def _revision_history(document: Document) -> None:
    heading = document.add_paragraph()
    heading.paragraph_format.space_before = Pt(12)
    _run(heading, "Revision history", bold=True, size=12, color=NAVY)
    _row_table(document, ["Rev", "Date", "Description", "By"], "revision_history", [14, 28, 100, 28])


def approval_note() -> None:
    document = Document()
    _header_footer(document, "Approval note")
    _banner(document, "APPROVAL NOTE")
    _control_table(document, [("Equipment / subject", "{{equipment}}")])
    for number, (title, key) in enumerate(
        [("Subject", "subject"), ("Background", "background"), ("Findings", "findings"),
         ("Analysis", "analysis"), ("Recommendation", "recommendation"), ("Annexures", "annexures")],
        start=1,
    ):
        _section(document, number, title, key)
    _sources(document, 7)
    _approval_block(document)
    _revision_history(document)
    document.core_properties.title = "Approval note (Citadel constructed template)"
    document.save(OUT / "approval-note.docx")


def inspection_summary() -> None:
    document = Document()
    _header_footer(document, "Inspection summary")
    _banner(document, "INSPECTION SUMMARY")
    _control_table(document, [])
    _section(document, 1, "Equipment tag", "equipment_tag")
    _section(document, 2, "Inspection date", "inspection_date")
    _section(document, 3, "Observations", "observations")
    heading = document.add_paragraph()
    heading.paragraph_format.space_before = Pt(10)
    _run(heading, "4. Defects", bold=True, size=12, color=NAVY)
    _row_table(document, ["Location", "Defect", "Measurement", "Ref"], "defects", [40, 70, 35, 25])
    document.add_paragraph()
    _section(document, 5, "Disposition", "disposition")
    _sources(document, 6)
    _revision_history(document)
    document.core_properties.title = "Inspection summary (Citadel constructed template)"
    document.save(OUT / "inspection-summary.docx")


def report() -> None:
    """A report shaped by its request: a title, a summary, then as many sections as the
    person asked for -- each with the heading the writer chose -- then recommendations
    and open questions. The body is ONE block placeholder the generator expands into
    sub-headings and paragraphs; everything around it is fixed, marked and numbered."""
    document = Document()
    _header_footer(document, "Report")
    _banner(document, "REPORT")
    _control_table(document, [])
    heading = document.add_paragraph()
    heading.paragraph_format.space_before = Pt(10)
    _run(heading, "Summary", bold=True, size=12, color=NAVY)
    body = document.add_paragraph()
    _run(body, "{{summary}}")
    rule = document.add_paragraph()
    rule.paragraph_format.space_before = Pt(6)
    body = document.add_paragraph()
    _run(body, "{{body}}")
    for title, key in (("Recommendations", "recommendations"), ("Open questions", "open_questions")):
        heading = document.add_paragraph()
        heading.paragraph_format.space_before = Pt(10)
        _run(heading, title, bold=True, size=12, color=NAVY)
        block = document.add_paragraph()
        _run(block, "{{" + key + "}}")
    _sources(document, None)
    _revision_history(document)
    document.core_properties.title = "Report (Citadel constructed template)"
    document.save(OUT / "report.docx")


def calculation_sheet() -> None:
    workbook = Workbook()
    sheet = workbook.active
    assert sheet is not None
    sheet.title = "Calculation"
    thin = Side(style="thin", color="8899AA")
    box = Border(left=thin, right=thin, top=thin, bottom=thin)
    head = PatternFill("solid", fgColor="D9E2EC")
    sheet.column_dimensions["A"].width = 30
    for col in "BCDE":
        sheet.column_dimensions[col].width = 22
    sheet["A1"] = "{{org_name}}"
    sheet["A1"].font = Font(bold=True, color="1D2B3A", size=11)
    sheet["E1"] = "{{classification}}"
    sheet["E1"].font = Font(bold=True, color="B01C24", size=12)
    sheet["A2"] = "CALCULATION SHEET"
    sheet["A2"].font = Font(bold=True, size=16, color="1D2B3A")
    sheet["A3"] = "{{subject_line}}"
    for row, (label, value) in enumerate(
        [("Document No.", "{{doc_number}}"), ("Revision", "{{revision}}"), ("Date", "{{date}}"),
         ("Prepared by", "{{prepared_by}}"), ("Citadel task", "{{task_ref}}")],
        start=5,
    ):
        sheet.cell(row=row, column=1, value=label).font = Font(bold=True)
        sheet.cell(row=row, column=2, value=value)
    sheet["A11"] = "INPUTS"
    sheet["A11"].font = Font(bold=True, color="1D2B3A")
    for col, text in enumerate(["Quantity", "Value", "Unit", "Source ref"], start=1):
        cell = sheet.cell(row=12, column=col, value=text)
        cell.font, cell.fill, cell.border = Font(bold=True), head, box
    sheet["A13"] = "{{inputs}}"
    sheet["A20"] = "WORKING"
    sheet["A20"].font = Font(bold=True, color="1D2B3A")
    for col, text in enumerate(["Step", "Expression", "Result", "Source ref"], start=1):
        cell = sheet.cell(row=21, column=col, value=text)
        cell.font, cell.fill, cell.border = Font(bold=True), head, box
    sheet["A22"] = "{{working}}"
    sheet["A30"] = "RESULT"
    sheet["A30"].font = Font(bold=True, color="1D2B3A")
    sheet["B30"] = "{{result}}"
    sheet["B30"].font = Font(bold=True, size=12)
    sheet["A32"] = "REFERENCES"
    sheet["A32"].font = Font(bold=True, color="1D2B3A")
    sheet["A33"] = "{{references}}"
    sheet["A40"] = "APPROVAL"
    sheet["A40"].font = Font(bold=True, color="1D2B3A")
    for row, (label, value) in enumerate(
        [("Prepared by", "{{prepared_by}}"), ("Approved by", "{{approved_by}}"), ("Approved on", "{{approved_on}}")],
        start=41,
    ):
        sheet.cell(row=row, column=1, value=label).font = Font(bold=True)
        sheet.cell(row=row, column=2, value=value).border = box
    # Sources: each bracketed reference resolves to a document version, page and
    # region, or to a recorded computation -- the same contract as the Word templates.
    sheet["A45"] = "SOURCES"
    sheet["A45"].font = Font(bold=True, color="1D2B3A")
    for col, text in enumerate(["Ref", "Source", "Version", "Page", "Region (x0, y0, x1, y1)"], start=1):
        cell = sheet.cell(row=46, column=col, value=text)
        cell.font, cell.fill, cell.border = Font(bold=True), head, box
    sheet["A47"] = "{{sources}}"
    for row in sheet.iter_rows(min_row=1, max_row=60):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
    # One page wide when printed, however many rows the working grows to.
    sheet.page_setup.orientation = "portrait"
    sheet.page_setup.paperSize = sheet.PAPERSIZE_A4
    sheet.sheet_properties.pageSetUpPr.fitToPage = True
    sheet.page_setup.fitToWidth = 1
    sheet.page_setup.fitToHeight = 0
    # The marking travels on every printed page, not only in the first cell.
    sheet.oddHeader.left.text = "{{org_name}}"
    sheet.oddHeader.right.text = "{{classification}}"
    sheet.oddFooter.center.text = "{{classification}}  |  Calculation sheet {{doc_number}} rev {{revision}}  |  page &P of &N"
    workbook.save(OUT / "calculation-sheet.xlsx")


BUILDERS = {
    "approval-note.docx": approval_note,
    "inspection-summary.docx": inspection_summary,
    "calculation-sheet.xlsx": calculation_sheet,
    "report.docx": report,
}


def main(argv: list[str] | tuple[str, ...] = ()) -> None:
    """Existing templates are left alone unless --force: an artifact's provenance names the
    template it was filled from, and a template rebuilt for no reason is a new template."""
    force = "--force" in argv
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for name, build in BUILDERS.items():
        if force or not (OUT / name).exists():
            build()
            written.append(name)
    print(f"templates in {OUT}: wrote {len(written)}" + (f": {', '.join(written)}" if written else ""))


if __name__ == "__main__":
    import sys

    main(sys.argv[1:])
